version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - teddy_data:/var/lib/postgresql/data
    networks:
      - teddy_network

  app:
    build: .
    container_name: app
    ports:
      - '3000:3000'
    environment:
      API_PORT: ${API_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - teddy_network
    depends_on:
      - postgres

volumes:
  teddy_data:

networks:
  teddy_network:
