version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: teddydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - teddy_data:/var/lib/postgresql/data
    networks:
      - teddy_network

volumes:
  teddy_data:

networks:
  teddy_network:
